### ISSUE TITLE
jib-maven-plugin out of date

### ISSUE THREAD

**Issue by fiidim** [spring-cloud/spring-cloud-dataflow-apps-plugin#9]
Generator version is currently `2.6.0` (October 2020).  Latest is `3.1.4`  (August 2021).  There seems to be enough meaningful changes to warrant an upgrade  [CHANGELOG.md](https://github.com/GoogleContainerTools/jib/blob/master/jib-maven-plugin/CHANGELOG.md).

There are 2 approaches that may be considered for this.   First would be to just increase the version in the 2 template files ([app-pom.xml](https://github.com/spring-cloud/spring-cloud-dataflow-apps-plugin/blob/main/spring-cloud-dataflow-apps-generator-plugin/src/main/resources/template/app-pom.xml)  and [app-modules-pom.xml](https://github.com/spring-cloud/spring-cloud-dataflow-apps-plugin/blob/main/spring-cloud-dataflow-apps-generator-plugin/src/main/resources/template/apps-modules-pom.xml)).  The second would be to allow the application project to specify the version, and default to a generator specified minimum version.

For both template files:
```xml
<version>{{#app.jibVersion}}{{.}}{{/app.jibVersion}}{{^app.jibVersion}}2.6.0{{/app.jibVersion}}</version>
```

Calling project would specify:
```xml
                    <application>
                        <name>aggregator</name>
                        <type>processor</type>
                        <version>${project.version}</version>
                        <configClass>org.springframework.cloud.fn.aggregator.AggregatorFunctionConfiguration.class</configClass>
                        <functionDefinition>aggregatorFunction</functionDefinition>
                        <jibVersion>3.1.4</jibVersion >
                        <maven>
                            <dependencies>
                                <dependency>
                                    <groupId>org.springframework.cloud.fn</groupId>
                                    <artifactId>aggregator-function</artifactId>
                                </dependency>
                            </dependencies>
                        </maven>
                    </application>
```

There aren't too many hard-coded versions in the generator, so it might be appropriate to allow the application project to dictate versions.

@tzolov  Thoughts?

**Comment by corneil** [comment]
#19 resolved this
